### ISSUE TITLE
Hello, I'd wanted to ask you a few questions about your nice project

### ISSUE THREAD

**Issue by heavyweaponsguy11** [urbamt/urbamt#30]
First: what that means?
    S -> NP VP
   NP -> PRP
   VP -> VB PP
Is it a basic english sentences structure? And second question: how your translator can be adapted for translating to more difficult languages (Russian or Ukrainian, for instance), where you need to use more cases for nouns (nominative, genetive, etc.)?

**Comment by patrickphat** [comment]
Hi @heavyweaponsguy11, 

Yes it is basic english grammar structure. For instance, S = subject, NP = noun phrase, VP = verb phrase, etc. But you can use any term that might be native to the language (Russian, Ukrainian).

If you're able to write the grammar structure of Russian and Ukranian language in this format, I think you could potentially can. I can quickly show you how to do that via an online call if you have time :)

**Comment by heavyweaponsguy11** [comment]
Thanks for the feedback, I really appreciate it!  Yes I think I can work on the grammar and rules, unfortunately I can't video call, but I can get some text instructions by email rxxt8888@gmail.com or on Reddit u/heavyweaponsguy11 :D
